import { Inter } from "next/font/google";
import "../styles/globals.css";
import Navbar from "../_components/_nav/Navbar";
import client from '../_api/sanity';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const navbarQuery = `*[_type == "navbar"] {
    title, 
    hasDropdown,
    link,
    links[] {
        link,title
    }
}|order(_createdAt desc)`;

export default async function RootLayout({ children }) {
    const navList = await client.fetch(navbarQuery);
    return (
        <html lang="en">
            <body className={inter.className} >
                {/* <div> main layout TEST!!</div> */}
                <Navbar navList={navList} />
                {children}
                <footer className="absolute bottom-0 w-full z-50 leading-loose bg-white">
                     © Apryse Software Inc.
                </footer>
            </body>
            
        </html>
    );
}
